### ISSUE TITLE
Setup Backend Server Environment

### ISSUE THREAD

**Issue by fufuShih** [ChillKa/chillka-backend#1]
## Goal

This issue is to establish a  backend server environment that supports our application's requirements.

## Tasks

- [x] Add linter and formmatter setting
- [x] Add git hooks setting
- [x] Setup express. with typescript
- [x] Setup connect in MongoDB
- [x] Lock the node version and package manager
